/**
 * AvatarArt — one face, eight paint jobs.
 *
 * Generated by outputs/gen_avatars.py. Edit the generator and re-run it — every
 * preset shares one piece of geometry, so a nudge here by hand is a nudge that
 * only lands on one avatar.
 */
import React, { memo, useId } from 'react';
import Svg, {
  ClipPath,
  Defs,
  Ellipse,
  G,
  LinearGradient,
  Path,
  RadialGradient,
  Stop,
} from 'react-native-svg';
import type { AvatarPreset } from './catalog';
import { HAIR } from './hair';

type Props = {
  preset: AvatarPreset;
  size?: number;
};

/**
 * Depth without a single blur: a radial skin gradient lit from the upper left, a
 * linear shade down the right cheek and under the jaw, a rim light stroked along
 * the silhouette and clipped inside it, and a shadow clipped to each eye so the
 * lid sits over the sclera. react-native-svg's filters are not worth trusting on
 * Android, and a gradient with a transparent outer stop costs nothing to
 * composite — so every soft edge here is one.
 *
 * Gradient and clip ids are namespaced per instance because SVG ids are global to
 * the document: two avatars sharing a `skin` id means the second silently
 * repaints the first, which is exactly what a picker rail would do.
 *
 * Memoised, and not as a reflex. One of these is 95 svg nodes — 13 gradients with
 * their 30 stops, 5 clip paths and 44 shapes — and the picker holds eight of them
 * plus a hero. Every tap in that card re-renders the picker, so without the memo
 * each tap walks all nine trees, 855 elements, to conclude that nothing changed.
 * Presets are module-level objects from catalog.ts, so the shallow compare is a
 * reference check and always hits.
 */
export default memo(function AvatarArt({ preset, size = 96 }: Props) {
  const c = preset.palette;
  const head =
    'M 60 25.5 C 74.5 25.5 86 36 86 51.5 C 86 65.5 81.5 77.5 72 84 C 68.5 86.8 64.5 88.2 60 88.2 C 55.5 88.2 51.5 86.8 48 84 C 38.5 77.5 34 65.5 34 51.5 C 34 36 45.5 25.5 60 25.5 Z';
  const hair = HAIR[preset.hair];
  const uid = useId().replace(/[^a-zA-Z0-9]/g, '');
  const url = (name: string) => `url(#${uid}-${name})`;

  return (
    <Svg width={size} height={size} viewBox="0 0 120 120">
      <Defs>
        <RadialGradient
          id={`${uid}-bg`}
          gradientUnits="userSpaceOnUse"
          cx="60"
          cy="60"
          r="66"
          fx="34"
          fy="26"
        >
          <Stop offset="0" stopColor={c.bgLight} />
          <Stop offset="1" stopColor={c.bgDeep} />
        </RadialGradient>
        <RadialGradient
          id={`${uid}-skin`}
          gradientUnits="userSpaceOnUse"
          cx="60"
          cy="54"
          r="40"
          fx="46"
          fy="34"
        >
          <Stop offset="0" stopColor={c.skinLight} />
          <Stop offset="0.62" stopColor={c.skin} />
          <Stop offset="1" stopColor={c.skinShade} />
        </RadialGradient>
        <LinearGradient
          id={`${uid}-side`}
          gradientUnits="userSpaceOnUse"
          x1="64"
          y1="38"
          x2="88"
          y2="68"
        >
          <Stop offset="0" stopColor={c.skinDeep} stopOpacity="0" />
          <Stop offset="1" stopColor={c.skinDeep} stopOpacity="0.3" />
        </LinearGradient>
        <LinearGradient
          id={`${uid}-chin`}
          gradientUnits="userSpaceOnUse"
          x1="60"
          y1="68"
          x2="60"
          y2="88"
        >
          <Stop offset="0" stopColor={c.skinDeep} stopOpacity="0" />
          <Stop offset="1" stopColor={c.skinDeep} stopOpacity="0.26" />
        </LinearGradient>
        <LinearGradient
          id={`${uid}-rim`}
          gradientUnits="userSpaceOnUse"
          x1="34"
          y1="34"
          x2="58"
          y2="76"
        >
          <Stop offset="0" stopColor="#ffffff" stopOpacity="0.55" />
          <Stop offset="1" stopColor="#ffffff" stopOpacity="0" />
        </LinearGradient>
        <LinearGradient
          id={`${uid}-hair`}
          gradientUnits="userSpaceOnUse"
          x1="36"
          y1="22"
          x2="84"
          y2="62"
        >
          <Stop offset="0" stopColor={c.hairLight} />
          <Stop offset="0.55" stopColor={c.hair} />
          <Stop offset="1" stopColor={c.hairDark} />
        </LinearGradient>
        <RadialGradient
          id={`${uid}-gloss`}
          gradientUnits="userSpaceOnUse"
          cx="47"
          cy="31"
          r="16"
          fx="43"
          fy="27"
        >
          <Stop offset="0" stopColor="#ffffff" stopOpacity="0.34" />
          <Stop offset="1" stopColor="#ffffff" stopOpacity="0" />
        </RadialGradient>
        <LinearGradient
          id={`${uid}-shirt`}
          gradientUnits="userSpaceOnUse"
          x1="28"
          y1="90"
          x2="98"
          y2="121"
        >
          <Stop offset="0" stopColor={c.shirtLight} />
          <Stop offset="0.5" stopColor={c.shirt} />
          <Stop offset="1" stopColor={c.shirtDark} />
        </LinearGradient>
        <RadialGradient
          id={`${uid}-nape`}
          gradientUnits="userSpaceOnUse"
          cx="60"
          cy="88"
          r="18"
          fx="60"
          fy="84"
        >
          <Stop offset="0" stopColor={c.skinDeep} stopOpacity="0.5" />
          <Stop offset="1" stopColor={c.skinDeep} stopOpacity="0" />
        </RadialGradient>
        <RadialGradient
          id={`${uid}-nose`}
          gradientUnits="userSpaceOnUse"
          cx="60"
          cy="67.6"
          r="5"
          fx="58.2"
          fy="65.4"
        >
          <Stop offset="0" stopColor={c.skinLight} />
          <Stop offset="0.55" stopColor={c.skin} />
          <Stop offset="1" stopColor={c.skinShade} />
        </RadialGradient>
        <LinearGradient
          id={`${uid}-lid`}
          gradientUnits="userSpaceOnUse"
          x1="60"
          y1="49"
          x2="60"
          y2="61"
        >
          <Stop offset="0" stopColor={c.skinDeep} stopOpacity="0.36" />
          <Stop offset="1" stopColor={c.skinDeep} stopOpacity="0" />
        </LinearGradient>
        <RadialGradient
          id={`${uid}-blushL`}
          gradientUnits="userSpaceOnUse"
          cx="42"
          cy="70"
          r="7.5"
          fx="42"
          fy="70"
        >
          <Stop offset="0" stopColor={c.blush} stopOpacity="0.6" />
          <Stop offset="1" stopColor={c.blush} stopOpacity="0" />
        </RadialGradient>
        <RadialGradient
          id={`${uid}-blushR`}
          gradientUnits="userSpaceOnUse"
          cx="78"
          cy="70"
          r="7.5"
          fx="78"
          fy="70"
        >
          <Stop offset="0" stopColor={c.blush} stopOpacity="0.6" />
          <Stop offset="1" stopColor={c.blush} stopOpacity="0" />
        </RadialGradient>
        <ClipPath id={`${uid}-disc`}>
          <Ellipse cx="60" cy="60" rx="60" ry="60" />
        </ClipPath>
        <ClipPath id={`${uid}-head`}>
          <Path d={head} />
        </ClipPath>
        <ClipPath id={`${uid}-eyeL`}>
          <Ellipse cx="49.4" cy="58" rx="6.6" ry="7.3" />
        </ClipPath>
        <ClipPath id={`${uid}-eyeR`}>
          <Ellipse cx="70.6" cy="58" rx="6.6" ry="7.3" />
        </ClipPath>
        <ClipPath id={`${uid}-hairFront`}>
          <Path d={hair.front} />
        </ClipPath>
      </Defs>
      <G clipPath={url('disc')}>
        <Ellipse cx="60" cy="60" rx="60" ry="60" fill={url('bg')} />
        {hair.back ? <Path d={hair.back} fill={url('hair')} /> : null}
        {hair.extra && hair.extraBehind ? (
          <Path d={hair.extra} fill={url('hair')} />
        ) : null}
        <Ellipse cx="34.2" cy="59" rx="4.4" ry="6.4" fill={c.skinShade} />
        <Ellipse cx="85.8" cy="59" rx="4.4" ry="6.4" fill={c.skinShade} />
        <Ellipse
          cx="35.1"
          cy="59"
          rx="2"
          ry="3.3"
          fill={c.skinDeep}
          opacity="0.32"
        />
        <Ellipse
          cx="84.9"
          cy="59"
          rx="2"
          ry="3.3"
          fill={c.skinDeep}
          opacity="0.32"
        />
        <Path
          d="M 51 73 C 51 85 49 94 43 108 L 77 108 C 71 94 69 85 69 73 Z"
          fill={c.skinShade}
        />
        <Ellipse cx="60" cy="88" rx="17" ry="9" fill={url('nape')} />
        <Path
          d="M 8 121 C 8 106 24 96.5 41 92.5 C 47 101 53.5 104.5 60 104.5 C 66.5 104.5 73 101 79 92.5 C 96 96.5 112 106 112 121 Z"
          fill={url('shirt')}
        />
        <Path
          d="M 41 92.5 C 47 101 53.5 104.5 60 104.5 C 66.5 104.5 73 101 79 92.5"
          stroke={c.shirtLight}
          strokeWidth="2.2"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          opacity="0.55"
        />
        <Path d={head} fill={url('skin')} />
        <Path d={head} fill={url('side')} />
        <Path d={head} fill={url('chin')} />
        <Path
          d={head}
          stroke={url('rim')}
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          clipPath={url('head')}
        />
        <Ellipse cx="42" cy="70" rx="7" ry="4.2" fill={url('blushL')} />
        <Ellipse cx="78" cy="70" rx="7" ry="4.2" fill={url('blushR')} />
        <Ellipse cx="49.4" cy="58" rx="6.6" ry="7.3" fill="#ffffff" />
        <Ellipse
          cx="49.4"
          cy="51.5"
          rx="6.6"
          ry="4.6"
          fill={url('lid')}
          clipPath={url('eyeL')}
        />
        <Ellipse cx="50.2" cy="59" rx="3.9" ry="3.9" fill="#4a3226" />
        <Ellipse cx="50.2" cy="59.4" rx="1.95" ry="1.95" fill="#181014" />
        <Ellipse
          cx="48"
          cy="55.8"
          rx="1.75"
          ry="1.5"
          fill="#ffffff"
          opacity="0.92"
        />
        <Ellipse
          cx="52"
          cy="61.4"
          rx="0.9"
          ry="0.8"
          fill="#ffffff"
          opacity="0.45"
        />
        <Ellipse cx="70.6" cy="58" rx="6.6" ry="7.3" fill="#ffffff" />
        <Ellipse
          cx="70.6"
          cy="51.5"
          rx="6.6"
          ry="4.6"
          fill={url('lid')}
          clipPath={url('eyeR')}
        />
        <Ellipse cx="69.8" cy="59" rx="3.9" ry="3.9" fill="#4a3226" />
        <Ellipse cx="69.8" cy="59.4" rx="1.95" ry="1.95" fill="#181014" />
        <Ellipse
          cx="72"
          cy="55.8"
          rx="1.75"
          ry="1.5"
          fill="#ffffff"
          opacity="0.92"
        />
        <Ellipse
          cx="68"
          cy="61.4"
          rx="0.9"
          ry="0.8"
          fill="#ffffff"
          opacity="0.45"
        />
        <Path
          d="M 41.2 48.6 C 43.4 44.2 51.6 43.2 56.2 46.4 C 55.4 47.9 54.6 48.4 53.6 48.2 C 49.6 47.2 45.2 47.9 42.6 50.4 Z"
          fill={c.brow}
        />
        <Path
          d="M 78.8 48.6 C 76.6 44.2 68.4 43.2 63.8 46.4 C 64.6 47.9 65.4 48.4 66.4 48.2 C 70.4 47.2 74.8 47.9 77.4 50.4 Z"
          fill={c.brow}
        />
        <Ellipse
          cx="60"
          cy="70.8"
          rx="4.6"
          ry="1.9"
          fill={c.skinDeep}
          opacity="0.16"
        />
        <Ellipse cx="60" cy="67.6" rx="3.6" ry="2.9" fill={url('nose')} />
        <Ellipse
          cx="58.5"
          cy="66.2"
          rx="1.1"
          ry="0.9"
          fill="#ffffff"
          opacity="0.45"
        />
        <Path
          d="M 50.5 74 C 54 73.4 66 73.4 69.5 74 C 68.4 81.6 64.2 85.4 60 85.4 C 55.8 85.4 51.6 81.6 50.5 74 Z"
          fill={c.mouth}
        />
        <Path
          d="M 51.2 74.2 C 54.4 73.7 65.6 73.7 68.8 74.2 C 67.2 78.6 52.8 78.6 51.2 74.2 Z"
          fill="#ffffff"
          opacity="0.94"
        />
        <Path d={hair.front} fill={url('hair')} />
        <Ellipse
          cx="47"
          cy="31"
          rx="15.5"
          ry="8.5"
          fill={url('gloss')}
          clipPath={url('hairFront')}
        />
        {hair.extra && !hair.extraBehind ? (
          <Path d={hair.extra} fill={url('hair')} />
        ) : null}
      </G>
    </Svg>
  );
});
