/**
 * The prebuilt avatar presets.
 *
 * Generated by outputs/gen_avatars.py. Edit the generator and re-run it — every
 * preset shares one piece of geometry, so a nudge here by hand is a nudge that
 * only lands on one avatar.
 */

import type { HairStyle } from './hair';

export type AvatarId =
  | 'boy-1'
  | 'boy-2'
  | 'boy-3'
  | 'boy-4'
  | 'girl-1'
  | 'girl-2'
  | 'girl-3'
  | 'girl-4';

export type AvatarGroup = 'boys' | 'girls';

/** Every shade the artwork needs, derived once by the generator. */
export type AvatarPalette = {
  skin: string;
  skinLight: string;
  skinShade: string;
  skinDeep: string;
  hair: string;
  hairLight: string;
  hairDark: string;
  shirt: string;
  shirtLight: string;
  shirtDark: string;
  bgLight: string;
  bgDeep: string;
  blush: string;
  brow: string;
  mouth: string;
};

export type AvatarPreset = {
  id: AvatarId;
  label: string;
  group: AvatarGroup;
  hair: HairStyle;
  palette: AvatarPalette;
};

export const AVATARS: readonly AvatarPreset[] = [
  {
    id: 'boy-1',
    label: 'Ali',
    group: 'boys',
    hair: 'crop',
    palette: {
      skin: '#f7d7bd',
      skinLight: '#f9dfca',
      skinShade: '#e1bca4',
      skinDeep: '#c79e87',
      hair: '#3a2318',
      hairLight: '#75655d',
      hairDark: '#261710',
      shirt: '#06b6d4',
      shirtLight: '#33c3dc',
      shirtDark: '#058aa1',
      bgLight: '#e1f6fa',
      bgDeep: '#a0e3ef',
      blush: '#eb9089',
      brow: '#301d14',
      mouth: '#8e4e4a',
    },
  },
  {
    id: 'boy-2',
    label: 'Bilal',
    group: 'boys',
    hair: 'quiff',
    palette: {
      skin: '#e3af83',
      skinLight: '#e9bf9c',
      skinShade: '#d09b73',
      skinDeep: '#ba8361',
      hair: '#1e1b21',
      hairLight: '#625f64',
      hairDark: '#141216',
      shirt: '#2a4763',
      shirtLight: '#50687f',
      shirtDark: '#20364b',
      bgLight: '#e5e9ec',
      bgDeep: '#aeb9c4',
      blush: '#e27e6f',
      brow: '#19161b',
      mouth: '#8a463f',
    },
  },
  {
    id: 'boy-3',
    label: 'Faraz',
    group: 'boys',
    hair: 'crop',
    palette: {
      skin: '#8f5c3d',
      skinLight: '#a57d64',
      skinShade: '#895538',
      skinDeep: '#834d32',
      hair: '#1e1b21',
      hairLight: '#625f64',
      hairDark: '#141216',
      shirt: '#e08a2e',
      shirtLight: '#e69f54',
      shirtDark: '#aa6923',
      bgLight: '#fbf1e6',
      bgDeep: '#f3d3b0',
      blush: '#bd5850',
      brow: '#19161b',
      mouth: '#7a3732',
    },
  },
  {
    id: 'boy-4',
    label: 'Hamza',
    group: 'boys',
    hair: 'quiff',
    palette: {
      skin: '#c78b5e',
      skinLight: '#d2a27e',
      skinShade: '#b87c54',
      skinDeep: '#a86c48',
      hair: '#8a3f22',
      hairLight: '#ad7964',
      hairDark: '#5b2a16',
      shirt: '#2f8f5b',
      shirtLight: '#54a379',
      shirtDark: '#246d45',
      bgLight: '#e6f2eb',
      bgDeep: '#b0d4c1',
      blush: '#d66d5f',
      brow: '#71341c',
      mouth: '#854038',
    },
  },
  {
    id: 'girl-1',
    label: 'Ayesha',
    group: 'girls',
    hair: 'long',
    palette: {
      skin: '#f7d7bd',
      skinLight: '#f9dfca',
      skinShade: '#e1bca4',
      skinDeep: '#c79e87',
      hair: '#3a2318',
      hairLight: '#75655d',
      hairDark: '#261710',
      shirt: '#e0728e',
      shirtLight: '#e68ba2',
      shirtDark: '#aa576c',
      bgLight: '#fbeef1',
      bgDeep: '#f3c9d4',
      blush: '#eb9089',
      brow: '#301d14',
      mouth: '#8e4e4a',
    },
  },
  {
    id: 'girl-2',
    label: 'Zainab',
    group: 'girls',
    hair: 'bun',
    palette: {
      skin: '#e3af83',
      skinLight: '#e9bf9c',
      skinShade: '#d09b73',
      skinDeep: '#ba8361',
      hair: '#1e1b21',
      hairLight: '#625f64',
      hairDark: '#141216',
      shirt: '#06b6d4',
      shirtLight: '#33c3dc',
      shirtDark: '#058aa1',
      bgLight: '#e1f6fa',
      bgDeep: '#a0e3ef',
      blush: '#e27e6f',
      brow: '#19161b',
      mouth: '#8a463f',
    },
  },
  {
    id: 'girl-3',
    label: 'Maryam',
    group: 'girls',
    hair: 'long',
    palette: {
      skin: '#8f5c3d',
      skinLight: '#a57d64',
      skinShade: '#895538',
      skinDeep: '#834d32',
      hair: '#1e1b21',
      hairLight: '#625f64',
      hairDark: '#141216',
      shirt: '#7b5cd6',
      shirtLight: '#9379dd',
      shirtDark: '#5d46a3',
      bgLight: '#efebfa',
      bgDeep: '#cdc1ef',
      blush: '#bd5850',
      brow: '#19161b',
      mouth: '#7a3732',
    },
  },
  {
    id: 'girl-4',
    label: 'Sana',
    group: 'girls',
    hair: 'bob',
    palette: {
      skin: '#c78b5e',
      skinLight: '#d2a27e',
      skinShade: '#b87c54',
      skinDeep: '#a86c48',
      hair: '#5b3320',
      hairLight: '#8c7063',
      hairDark: '#3c2215',
      shirt: '#12a08f',
      shirtLight: '#3db1a3',
      shirtDark: '#0e7a6d',
      bgLight: '#e3f4f2',
      bgDeep: '#a5dbd4',
      blush: '#d66d5f',
      brow: '#4b2a1a',
      mouth: '#854038',
    },
  },
];

/**
 * Presets in the order the picker shows them, one row per group.
 */
export const AVATAR_GROUPS: readonly {
  group: AvatarGroup;
  label: string;
  presets: readonly AvatarPreset[];
}[] = [
  {
    group: 'boys',
    label: 'Male',
    presets: AVATARS.filter(a => a.group === 'boys'),
  },
  {
    group: 'girls',
    label: 'Female',
    presets: AVATARS.filter(a => a.group === 'girls'),
  },
];

/**
 * A stored avatar id is only ever a hint: presets can be renamed or dropped,
 * and the profile document keeps whatever was chosen at the time. An unknown
 * id therefore reads as 'no avatar' rather than throwing on render.
 */
export function findAvatar(id: string | null | undefined): AvatarPreset | null {
  if (!id) return null;
  return AVATARS.find(preset => preset.id === id) ?? null;
}
