/**
 * Hairstyle path data for the prebuilt avatars.
 *
 * Generated by outputs/gen_avatars.py. Edit the generator and re-run it — every
 * preset shares one piece of geometry, so a nudge here by hand is a nudge that
 * only lands on one avatar.
 */

export type HairStyle = 'crop' | 'quiff' | 'long' | 'bob' | 'bun';

export type HairPaths = {
  /** The cap over the forehead, drawn after the face. */
  front: string;
  /** Mass behind the skull, drawn before it so it shows past the cheeks. */
  back: string | null;
  /** A bun or a quiff; `extraBehind` says which side of the head it lands on. */
  extra: string | null;
  extraBehind: boolean;
};

export const HAIR: Record<HairStyle, HairPaths> = {
  crop: {
    front:
      'M 31.8 57 C 31.2 34.6 44.4 22.4 60 22.4 C 75.6 22.4 88.8 34.6 88.2 57 C 87.4 48.4 84.6 44.4 80.4 42.4 C 73.4 39 52.6 39.2 46.6 43.8 C 41.2 47 33 49 31.8 57 Z',
    back: null,
    extra: null,
    extraBehind: false,
  },
  quiff: {
    front:
      'M 31.8 58 C 30.8 42 32.4 29.6 39.6 23 C 44.6 17.6 50 15.2 56.4 15.6 C 68.4 16.4 78.4 24.6 82.6 34 C 86.2 42 88.4 49 88.2 58 C 87.6 50 86.4 43.6 81.4 44.6 C 73.4 42 60 40 50.4 38.6 C 42 40 32.8 47 31.8 58 Z',
    back: null,
    extra: null,
    extraBehind: false,
  },
  long: {
    front:
      'M 32.8 56 C 32.8 34 45 22.6 60 22.6 C 75 22.6 87.2 34 87.2 56 C 86 43.4 78.4 37.2 68.6 35.6 C 64.4 40 62 46 60.8 52.6 C 59 46 56 40 51.6 35.6 C 42 37.6 34 43.4 32.8 56 Z',
    back: 'M 25.6 64 C 25.6 37.6 41 19.6 60 19.6 C 79 19.6 94.4 37.6 94.4 64 C 94.4 84 90.6 100.4 86.6 112 L 33.4 112 C 29.4 100.4 25.6 84 25.6 64 Z',
    extra: null,
    extraBehind: false,
  },
  bob: {
    front:
      'M 32.8 56 C 32.8 34 45 22.6 60 22.6 C 75 22.6 87.2 34 87.2 56 C 86 41.6 74.4 33.4 59.6 39.6 C 49.6 43.8 39.4 48 32.8 56 Z',
    back: 'M 27.6 62.4 C 27.6 37.6 42 21.6 60 21.6 C 78 21.6 92.4 37.6 92.4 62.4 C 92.4 77 90.4 85.6 86 91.4 C 80.4 85.6 80 75 80 66 L 40 66 C 40 75 39.6 85.6 34 91.4 C 29.6 85.6 27.6 77 27.6 62.4 Z',
    extra: null,
    extraBehind: false,
  },
  bun: {
    front:
      'M 32.8 56 C 32.8 34 45 22.6 60 22.6 C 75 22.6 87.2 34 87.2 56 C 87.2 44 76 37.6 60 37.6 C 44 37.6 32.8 44 32.8 56 Z',
    back: null,
    extra:
      'M 71.6 16.4 C 71.6 22.14 66.41 26.8 60 26.8 C 53.59 26.8 48.4 22.14 48.4 16.4 C 48.4 10.66 53.59 6 60 6 C 66.41 6 71.6 10.66 71.6 16.4 Z',
    extraBehind: true,
  },
};
