/**
 * Tiling on the mart floor.
 *
 * Generated by outputs/gen_backdrop.py — re-run it rather than hand-editing.
 *
 * A grid on the scene's own ground axes, clipped to the floor's silhouette, so
 * the joints run along the same two directions every shadow and every fixture
 * does. That shared vanishing is the whole point: a floor with no grain reads as
 * a white blob, and a grid on any other axis reads as a sticker.
 *
 * The viewBox is the floor layer's own box, so this drops in beside <Floor /> and
 * rides the floor's rise without any positioning of its own. It fills absolutely
 * rather than at 100%/100% because it is the second child of that layer: at 100%
 * height it would be laid out *below* the floor instead of over it.
 */
import { memo } from 'react';
import { StyleSheet } from 'react-native';
import Svg, { ClipPath, Defs, G, Line, Path } from 'react-native-svg';

const FLOOR =
  'M77.66,242.46c-95.18,55-95.17,144,0,199s249.49,54.95,344.67,0,95.17-144,0-199S172.84,187.5,77.66,242.46Z';

/** Each joint, already trimmed to the floor so nothing is drawn to be clipped. */
const JOINT: readonly (readonly [number, number, number, number])[] = [
  [350.34, 209.93, 447.45, 266],
  [259.5, 195.48, 478.74, 322.06],
  [199.59, 198.9, 479.08, 360.26],
  [151.78, 209.29, 467.34, 391.48],
  [112.11, 224.39, 447.45, 418],
  [79.16, 243.36, 420.84, 440.64],
  [52.55, 266, 387.89, 459.61],
  [32.66, 292.52, 348.22, 474.71],
  [20.92, 323.74, 300.41, 485.1],
  [21.26, 361.94, 240.5, 488.52],
  [52.55, 418, 149.66, 474.07],
  [149.66, 209.93, 52.55, 266],
  [240.5, 195.48, 21.26, 322.06],
  [300.41, 198.9, 20.92, 360.26],
  [348.22, 209.29, 32.66, 391.48],
  [387.89, 224.39, 52.55, 418],
  [420.84, 243.36, 79.16, 440.64],
  [447.45, 266, 112.11, 459.61],
  [467.34, 292.52, 151.78, 474.71],
  [479.08, 323.74, 199.59, 485.1],
  [478.74, 361.94, 259.5, 488.52],
  [447.45, 418, 350.34, 474.07],
];

function FloorTiles() {
  return (
    <Svg style={StyleSheet.absoluteFill} viewBox="3 199 494 287">
      <Defs>
        <ClipPath id="martFloorClip">
          <Path d={FLOOR} />
        </ClipPath>
      </Defs>
      <G
        clipPath="url(#martFloorClip)"
        stroke="#D5DCE1"
        strokeWidth={0.9}
        opacity={0.5}
      >
        {JOINT.map(([x1, y1, x2, y2], i) => (
          <Line key={i} x1={x1} y1={y1} x2={x2} y2={y2} />
        ))}
      </G>
    </Svg>
  );
}

export default memo(FloorTiles);
