/**
 * The room the illustration stands in.
 *
 * Generated by outputs/gen_backdrop.py — re-run it rather than hand-editing the
 * geometry below.
 *
 * On the bare cyan field the artwork reads fine, so this is not a rescue: it is
 * a *place*. Without it the fixtures and people float on a colour. Every piece of
 * invented geometry sits on the same two ground axes measured off the drawn
 * shadows — u = (+cos30, +0.5), v = (-cos30, +0.5) — so the far shelving shares a
 * room with the drawn shelving instead of merely sitting behind it.
 *
 * Back to front: the far aisle row, a vignette *over* it so the row falls into
 * shade at the edges, then the ceiling spill (light does not get vignetted, so it
 * goes on top), then a halo concentric with the floor so the floor's white rim
 * does not cut hard into the cyan.
 *
 * It covers the whole screen, not the scene's slot. The illustration is square and
 * the screen is not, so a room that stopped at the slot would leave a hard edge
 * between the room and the flat field below it. Filling the screen instead puts the
 * copy inside the room — vignetted at the corners, lit near the floor — and the
 * seam disappears. Only the geometry stays tied to the scene: the aisles and the
 * halo are placed in scene units, so they stay registered to the drawn floor no
 * matter how much screen there is around it.
 *
 * The row is deliberately ~7% contrast against the field. Anything more legible
 * back there competes with the illustration and starts to look like clipart; this
 * faint it reads as architecture at a distance. The horizontal lines across each
 * front face are what make a slab read as shelving.
 *
 * It fades in, and only fades. A room that slid or scaled would be the one element
 * in the scene contradicting the fact that the camera is not moving.
 *
 * The fade runs on a hardware texture. Four radial gradients over a screen-sized
 * rect is the most expensive thing to draw in the whole scene and none of it ever
 * changes, so it is drawn once and the 900ms fade is an alpha applied to the result
 * rather than 54 frames of re-shading.
 */
import { memo } from 'react';
import { StyleSheet } from 'react-native';
import Animated, {
  useAnimatedStyle,
  type SharedValue,
} from 'react-native-reanimated';
import Svg, {
  Defs,
  Ellipse,
  G,
  Line,
  Polygon,
  RadialGradient,
  Rect,
  Stop,
} from 'react-native-svg';
import type { Layout } from './geometry';

/** Faces of the far shelving: front along u, end along -v, then the top. */
const FACE: readonly (readonly [string, string])[] = [
  ['-46,205 26.75,247 26.75,102 -46,60', '#17A7D2'],
  ['26.75,247 49.26,234 49.26,89 26.75,102', '#0B93C0'],
  ['-46,60 26.75,102 49.26,89 -23.48,47', '#2FB6DD'],
  ['42,205 104.35,241 104.35,96 42,60', '#17A7D2'],
  ['104.35,241 123.41,230 123.41,85 104.35,96', '#0B93C0'],
  ['42,60 104.35,96 123.41,85 61.05,49', '#2FB6DD'],
  ['130,205 209.67,251 209.67,106 130,60', '#17A7D2'],
  ['209.67,251 233.06,237.5 233.06,92.5 209.67,106', '#0B93C0'],
  ['130,60 209.67,106 233.06,92.5 153.38,46.5', '#2FB6DD'],
  ['218,205 285.55,244 285.55,99 218,60', '#17A7D2'],
  ['285.55,244 305.47,232.5 305.47,87.5 285.55,99', '#0B93C0'],
  ['218,60 285.55,99 305.47,87.5 237.92,48.5', '#2FB6DD'],
  ['306,205 382.21,249 382.21,104 306,60', '#17A7D2'],
  ['382.21,249 403.86,236.5 403.86,91.5 382.21,104', '#0B93C0'],
  ['306,60 382.21,104 403.86,91.5 327.65,47.5', '#2FB6DD'],
  ['394,205 454.62,240 454.62,95 394,60', '#17A7D2'],
  ['454.62,240 472.81,229.5 472.81,84.5 454.62,95', '#0B93C0'],
  ['394,60 454.62,95 472.81,84.5 412.19,49.5', '#2FB6DD'],
  ['482,205 553.01,246 553.01,101 482,60', '#17A7D2'],
  ['553.01,246 573.8,234 573.8,89 553.01,101', '#0B93C0'],
  ['482,60 553.01,101 573.8,89 502.78,48', '#2FB6DD'],
  ['570,205 635.82,243 635.82,98 570,60', '#17A7D2'],
  ['635.82,243 654.87,232 654.87,87 635.82,98', '#0B93C0'],
  ['570,60 635.82,98 654.87,87 589.05,49', '#2FB6DD'],
];

/** Shelf lines across each front face. */
const LINE: readonly (readonly [number, number, number, number])[] = [
  [-46, 161.5, 26.75, 203.5],
  [-46, 125.25, 26.75, 167.25],
  [-46, 91.9, 26.75, 133.9],
  [42, 161.5, 104.35, 197.5],
  [42, 125.25, 104.35, 161.25],
  [42, 91.9, 104.35, 127.9],
  [130, 161.5, 209.67, 207.5],
  [130, 125.25, 209.67, 171.25],
  [130, 91.9, 209.67, 137.9],
  [218, 161.5, 285.55, 200.5],
  [218, 125.25, 285.55, 164.25],
  [218, 91.9, 285.55, 130.9],
  [306, 161.5, 382.21, 205.5],
  [306, 125.25, 382.21, 169.25],
  [306, 91.9, 382.21, 135.9],
  [394, 161.5, 454.62, 196.5],
  [394, 125.25, 454.62, 160.25],
  [394, 91.9, 454.62, 126.9],
  [482, 161.5, 553.01, 202.5],
  [482, 125.25, 553.01, 166.25],
  [482, 91.9, 553.01, 132.9],
  [570, 161.5, 635.82, 199.5],
  [570, 125.25, 635.82, 163.25],
  [570, 91.9, 635.82, 129.9],
];

type Props = {
  layout: Layout;
  /** The area to cover, dp. The whole screen, not the scene's slot. */
  width: number;
  height: number;
  progress: SharedValue<number>;
};

/**
 * The light pooled under the floor: concentric with the drawn floor and 13%
 * wider, so the floor's white rim is lifted off the cyan instead of cutting into
 * it. Named rather than inlined because the numbers come from the floor's own
 * ellipse, and a reader should be able to see that they are not free parameters.
 */
const HALO = { cx: 250, cy: 342, rx: 250.86, ry: 159.33 };

function MartBackdrop({ layout: l, width, height, progress }: Props) {
  // The covered area, expressed in scene units. The layout knows where the scene
  // square sits and how many dp there are to a scene unit, so dividing through by
  // k turns "the whole screen" into a viewBox the invented geometry can be placed
  // in — which is what keeps the halo concentric with the *drawn* floor instead of
  // with the middle of whatever screen this is.
  const x = -l.x / l.k;
  const y = -l.y / l.k;
  const w = width / l.k;
  const h = height / l.k;

  const fade = useAnimatedStyle(() => ({ opacity: progress.value }));

  return (
    <Animated.View
      pointerEvents="none"
      renderToHardwareTextureAndroid
      style={[StyleSheet.absoluteFill, fade]}
    >
      <Svg style={StyleSheet.absoluteFill} viewBox={`${x} ${y} ${w} ${h}`}>
        <Defs>
          <RadialGradient id="mbVig" cx="50%" cy="50%" r="50%">
            <Stop offset="0" stopColor="#00658C" stopOpacity="0" />
            <Stop offset="0.52" stopColor="#00658C" stopOpacity="0" />
            <Stop offset="0.8" stopColor="#00658C" stopOpacity="0.22" />
            <Stop offset="1" stopColor="#00658C" stopOpacity="0.55" />
          </RadialGradient>
          <RadialGradient id="mbCeil0" cx="50%" cy="50%" r="50%">
            <Stop offset="0" stopColor="#FFFFFF" stopOpacity="0.16" />
            <Stop offset="0.55" stopColor="#FFFFFF" stopOpacity="0.07" />
            <Stop offset="1" stopColor="#FFFFFF" stopOpacity="0" />
          </RadialGradient>
          <RadialGradient id="mbCeil1" cx="50%" cy="50%" r="50%">
            <Stop offset="0" stopColor="#FFFFFF" stopOpacity="0.13" />
            <Stop offset="0.55" stopColor="#FFFFFF" stopOpacity="0.05" />
            <Stop offset="1" stopColor="#FFFFFF" stopOpacity="0" />
          </RadialGradient>
          <RadialGradient id="mbHalo" cx="50%" cy="50%" r="50%">
            <Stop offset="0" stopColor="#FFFFFF" stopOpacity="0" />
            <Stop offset="0.74" stopColor="#FFFFFF" stopOpacity="0" />
            <Stop offset="0.9" stopColor="#FFFFFF" stopOpacity="0.3" />
            <Stop offset="1" stopColor="#FFFFFF" stopOpacity="0" />
          </RadialGradient>
        </Defs>
        {FACE.map(([points, fill], i) => (
          <Polygon key={`f${i}`} points={points} fill={fill} />
        ))}
        <G stroke="#0A8CB8" strokeWidth={1.6} opacity={0.55}>
          {LINE.map(([x1, y1, x2, y2], i) => (
            <Line key={`l${i}`} x1={x1} y1={y1} x2={x2} y2={y2} />
          ))}
        </G>
        <Rect x={x} y={y} width={w} height={h} fill="url(#mbVig)" />
        <Ellipse cx={148} cy={8} rx={132} ry={150} fill="url(#mbCeil0)" />
        <Ellipse cx={366} cy={-6} rx={122} ry={140} fill="url(#mbCeil1)" />
        <Ellipse {...HALO} fill="url(#mbHalo)" />
      </Svg>
    </Animated.View>
  );
}

export default memo(MartBackdrop);
