/* eslint-disable */
// Generated by outputs/gen_scene_art.py — every layer's own bounds inside
// the shared 500-unit illustration, in the order they stack.
//
// x/y/w/h are viewBox units. A wrapper positions the layer at these
// coordinates scaled by the scene size, which puts the layer's transform
// origin at its own centre.

export type ArtBox = { x: number; y: number; w: number; h: number };

export const ART_BOX = {
  floor: { x: 3, y: 199, w: 494, h: 287 },
  shelf: { x: 48, y: 58, w: 169, h: 321 },
  freezer: { x: 343, y: 63, w: 141, h: 309 },
  woman: { x: 94, y: 155, w: 141, h: 247 },
  man: { x: 234, y: 143, w: 203, h: 298 },
  baskets: { x: 17, y: 280, w: 67, h: 122 },
  shelfShadow: { x: 43, y: 293, w: 156, h: 93 },
  freezerShadow: { x: 341, y: 289, w: 150, h: 89 },
  basketsShadow: { x: 18, y: 365, w: 65, h: 40 },
  womanShadow: { x: 128, y: 352, w: 104, h: 63 },
  manShadow: { x: 222, y: 343, w: 105, h: 63 },
  cartShadow: { x: 285, y: 366, w: 139, h: 83 },
  cartInnerShadow: { x: 263, y: 248, w: 118, h: 71 },
} as const satisfies Record<string, ArtBox>;
